import type { RankingCard } from "@/types/ranking";

export const absurdistRankings: RankingCard[] = [
  {
    id: "pais-mas-flaco",
    tipo: "absurdo",
    titulo: "País más largo y flaco del mundo",
    descripcion: "4.300 km de largo, 177 km de ancho promedio. Un fideo con bandera.",
    valor: "#1 mundial",
    url: "https://en.wikipedia.org/wiki/Chile",
  },
  {
    id: "desierto-mas-arido",
    tipo: "absurdo",
    titulo: "Desierto más árido del planeta",
    descripcion: "El Atacama lleva millones de años perfeccionando la sequedad.",
    valor: "0 mm/año en zonas núcleo",
    fuente: "NASA",
    url: "https://en.wikipedia.org/wiki/Atacama_Desert",
  },
  {
    id: "poetas-nobel",
    tipo: "absurdo",
    titulo: "Más premios Nobel de Literatura per cápita en Latinoamérica",
    descripcion: "Mistral y Neruda. Dos. Con 19 millones de habitantes. Hagan el cálculo.",
    valor: "2 premios Nobel",
    url: "https://en.wikipedia.org/wiki/List_of_Nobel_laureates_by_country",
  },
  {
    id: "astronomos-per-capita",
    tipo: "absurdo",
    titulo: "Mayor concentración de astrónomos por habitante",
    descripcion: "El 40% de la observación astronómica mundial ocurre en suelo chileno.",
    valor: "40% del cielo mundial",
    fuente: "ESO",
    url: "https://en.wikipedia.org/wiki/Astronomy_in_Chile",
  },
  {
    id: "copa-america",
    tipo: "absurdo",
    titulo: "Bicampeón Copa América consecutivo",
    descripcion: "2015 y 2016. Argentina sabe lo que pasó.",
    valor: "2 títulos seguidos",
    url: "https://en.wikipedia.org/wiki/Copa_Am%C3%A9rica",
  },
  {
    id: "terremotos",
    tipo: "absurdo",
    titulo: "País con el terremoto más grande jamás registrado",
    descripcion: "Valdivia 1960, 9.5 Richter. Ni siquiera fue noticia por mucho tiempo.",
    valor: "9.5 Mw — récord mundial",
    fuente: "USGS",
    url: "https://en.wikipedia.org/wiki/1960_Valdivia_earthquake",
  },
  {
    id: "litio",
    tipo: "absurdo",
    titulo: "Mayor reserva de litio del mundo",
    descripcion: "El futuro eléctrico del planeta está bajo el Salar de Atacama.",
    valor: "~37% reservas globales",
    fuente: "USGS 2023",
    url: "https://en.wikipedia.org/wiki/Lithium_triangle",
  },
  {
    id: "mayonesa",
    tipo: "absurdo",
    titulo: "Mayor consumidor de mayonesa en Latinoamérica",
    descripcion: "Completo, chorrillana, papas fritas. La mayonesa no es condimento, es cultura.",
    valor: "#1 Latinoamérica",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "piscola",
    tipo: "absurdo",
    titulo: "Único país que mezcla pisco con Coca-Cola y le llama trago nacional",
    descripcion: "Perú disputa el pisco. Nadie le disputa la piscola.",
    valor: "Invención 100% chilena",
    url: "https://en.wikipedia.org/wiki/Pisco_sour",
  },
  {
    id: "empanadas",
    tipo: "absurdo",
    titulo: "País con más variantes de empanada por km² de territorio",
    descripcion: "Pino, queso, mariscos, manjar. Cada región tiene la suya y todas son la mejor.",
    valor: "Incontables variantes",
    url: "https://en.wikipedia.org/wiki/Empanada",
  },
];
