import type { RankingCard } from "@/types/ranking";

export const absurdistRankings: RankingCard[] = [
  {
    id: "pais-mas-flaco",
    tipo: "absurdo",
    titulo: "País más largo y flaco del mundo",
    descripcion: "4.300 km de largo, 177 km de ancho promedio. Un fideo con bandera.",
    valor: "#1 mundial",
    url: "https://en.wikipedia.org/wiki/Chile",
  },
  {
    id: "desierto-mas-arido",
    tipo: "absurdo",
    titulo: "Desierto más árido del planeta",
    descripcion: "El Atacama lleva millones de años perfeccionando la sequedad. Ni Marte se atreve tanto.",
    valor: "0 mm/año en zonas núcleo",
    fuente: "NASA",
    url: "https://en.wikipedia.org/wiki/Atacama_Desert",
  },
  {
    id: "poetas-nobel",
    tipo: "absurdo",
    titulo: "Más premios Nobel de Literatura per cápita en Latinoamérica",
    descripcion: "Mistral y Neruda. Dos. Con 19 millones de habitantes. Hagan el cálculo.",
    valor: "2 premios Nobel",
    url: "https://en.wikipedia.org/wiki/List_of_Nobel_laureates_by_country",
  },
  {
    id: "astronomos-per-capita",
    tipo: "absurdo",
    titulo: "Mayor concentración de astrónomos por habitante",
    descripcion: "El 40% de la observación astronómica mundial ocurre en suelo chileno. Los aliens nos eligen primero.",
    valor: "40% del cielo mundial",
    fuente: "ESO",
    url: "https://en.wikipedia.org/wiki/Astronomy_in_Chile",
  },
  {
    id: "copa-america",
    tipo: "absurdo",
    titulo: "Bicampeón Copa América consecutivo",
    descripcion: "2015 y 2016. Argentina sabe lo que pasó. Messi todavía lo recuerda.",
    valor: "2 títulos seguidos",
    url: "https://en.wikipedia.org/wiki/Copa_Am%C3%A9rica",
  },
  {
    id: "terremotos",
    tipo: "absurdo",
    titulo: "País con el terremoto más grande jamás registrado",
    descripcion: "Valdivia 1960, 9.5 Richter. Ni siquiera fue noticia por mucho tiempo. Los chilenos seguimos como si nada.",
    valor: "9.5 Mw — récord mundial",
    fuente: "USGS",
    url: "https://en.wikipedia.org/wiki/1960_Valdivia_earthquake",
  },
  {
    id: "litio",
    tipo: "absurdo",
    titulo: "Mayor reserva de litio del mundo",
    descripcion: "El futuro eléctrico del planeta está bajo el Salar de Atacama. Tesla nos debe un asado.",
    valor: "~37% reservas globales",
    fuente: "USGS 2023",
    url: "https://en.wikipedia.org/wiki/Lithium_triangle",
  },
  {
    id: "mayonesa",
    tipo: "absurdo",
    titulo: "Mayor consumidor de mayonesa en Latinoamérica",
    descripcion: "Completo, chorrillana, papas fritas. La mayonesa no es condimento, es cultura.",
    valor: "#1 Latinoamérica",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "piscola",
    tipo: "absurdo",
    titulo: "Único país que mezcla pisco con Coca-Cola y le llama trago nacional",
    descripcion: "Perú disputa el pisco. Nadie le disputa la piscola. Es nuestra.",
    valor: "Invención 100% chilena",
    url: "https://en.wikipedia.org/wiki/Pisco_sour",
  },
  {
    id: "empanadas",
    tipo: "absurdo",
    titulo: "País con más variantes de empanada por km² de territorio",
    descripcion: "Pino, queso, mariscos, manjar. Cada región tiene la suya y todas son la mejor.",
    valor: "Incontables variantes",
    url: "https://en.wikipedia.org/wiki/Empanada",
  },
  {
    id: "piscina-san-alfonso",
    tipo: "absurdo",
    titulo: "Piscina más grande del mundo",
    descripcion: "1.000 metros de largo, 66 millones de galones de agua de mar. Costó mil millones de dólares. Es solo para no perder la costumbre del Pacífico.",
    valor: "8 ha de piscina",
    url: "https://en.wikipedia.org/wiki/San_Alfonso_del_Mar",
  },
  {
    id: "rescate-mineros",
    tipo: "absurdo",
    titulo: "Mayor cantidad de mineros rescatados en vivo por CNN",
    descripcion: "33 mineros, 69 días, 700 metros. La NASA nos pidió consejos. Capitán Urzúa entregó el turno al Presidente.",
    valor: "33/33 rescatados",
    url: "https://en.wikipedia.org/wiki/2010_Copiap%C3%B3_mining_accident",
  },
  {
    id: "momias-chinchorro",
    tipo: "absurdo",
    titulo: "Momias más antiguas del planeta",
    descripcion: "Las momias Chinchorro tienen 7.000 años. Egipto nos copió el manual y se llevó el crédito.",
    valor: "7.000 años a.C.",
    url: "https://en.wikipedia.org/wiki/Chinchorro_mummies",
  },
  {
    id: "habitacion-mas-antigua",
    tipo: "absurdo",
    titulo: "Habitación humana más antigua de América",
    descripcion: "Monte Verde, 16.500 a.C. Los chilenos ya estábamos reclamando antes de que existieran las fronteras.",
    valor: "16.500 a.C.",
    url: "https://en.wikipedia.org/wiki/Monte_Verde",
  },
  {
    id: "telescopios",
    tipo: "absurdo",
    titulo: "Capital mundial de la astronomía",
    descripcion: "ALMA, VLT, E-ELT. Si hay vida extraterrestre, la primera señal la recibe un chileno con bufanda en el desierto.",
    valor: "70% telescopios principales",
    url: "https://en.wikipedia.org/wiki/Astronomy_in_Chile",
  },
  {
    id: "vino-carmenere",
    tipo: "absurdo",
    titulo: "Rescatadores oficiales de la uva Carmenère",
    descripcion: "Dada por extinta en Francia. La encontramos en Chile. Ahora es nuestra. Lo siento, Burdeos.",
    valor: "Patrimonio vitivinícola",
    url: "https://en.wikipedia.org/wiki/Carmen%C3%A8re",
  },
  {
    id: "salmon",
    tipo: "absurdo",
    titulo: "Segundo productor de salmón del mundo",
    descripcion: "Después de Noruega, pero con mejor vista. Los fiordes chilenos tienen alma.",
    valor: "#2 mundial",
    url: "https://en.wikipedia.org/wiki/Aquaculture_in_Chile",
  },
  {
    id: "cobre",
    tipo: "absurdo",
    titulo: "Mayor productor de cobre del mundo",
    descripcion: "Sin Chile no hay cables eléctricos, no hay internet, no hay civilización moderna. De nada.",
    valor: "~28% producción global",
    fuente: "USGS",
    url: "https://en.wikipedia.org/wiki/Mining_in_Chile",
  },
  {
    id: "isla-pascua",
    tipo: "absurdo",
    titulo: "Isla habitada más remota del planeta",
    descripcion: "3.500 km de cualquier continente. Los moai llevan mil años mirando al horizonte esperando delivery.",
    valor: "Rapa Nui, Chile",
    url: "https://en.wikipedia.org/wiki/Easter_Island",
  },
  {
    id: "moai",
    tipo: "absurdo",
    titulo: "Mayor cantidad de estatuas gigantes que no hicieron los egipcios",
    descripcion: "Casi 1.000 moai. Construidos, transportados y derribados antes de que Europa supiera escribir bien.",
    valor: "~1.000 estatuas",
    url: "https://en.wikipedia.org/wiki/Moai",
  },
  {
    id: "ojos-del-salado",
    tipo: "absurdo",
    titulo: "Volcán más alto del mundo",
    descripcion: "6.893 metros. Es tan alto que el oxígeno pide permiso para entrar. Y sigue activo.",
    valor: "6.893 msnm",
    url: "https://en.wikipedia.org/wiki/Ojos_del_Salado",
  },
  {
    id: "completo",
    tipo: "absurdo",
    titulo: "Hot dog con más ingredientes por metro cuadrado",
    descripcion: "Tomate, palta, chucrut, americana, mayo, cebolla. En otros países es pan con salchicha. Aquí es arte.",
    valor: "Completo italiano",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "marraqueta",
    tipo: "absurdo",
    titulo: "Pan con más poder de absorción de manteca del hemisferio sur",
    descripcion: "La marraqueta no es pan. Es un vehículo para transmitir palta y mantequilla al alma.",
    valor: "4 hallullas por persona/día",
    url: "https://en.wikipedia.org/wiki/Marraqueta",
  },
  {
    id: "pan-por-capita",
    tipo: "absurdo",
    titulo: "Segundo mayor consumo de pan per cápita del mundo",
    descripcion: "Después de Alemania, pero sin Oktoberfest. Solo once, empanadas y respeto.",
    valor: "#2 mundial",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "tostador-chileno",
    tipo: "absurdo",
    titulo: "Inventores del tostador de pan cilíndrico",
    descripcion: "Años 20. Una caja de lata con ranuras. Simple, elegante, indestructible. El diseño chileno en su máxima expresión.",
    valor: "Patrimonio doméstico",
    url: "https://es.wikipedia.org/wiki/Tostador_de_pan_chileno",
  },
  {
    id: "terremoto-bebida",
    tipo: "absurdo",
    titulo: "Único país donde un terremoto es algo que pides en la barra",
    descripcion: "Pipeño, helado de piña, un litro de vidrio. Después viene la réplica. Ningún otro país entiende esto.",
    valor: "Bebida nacional post-18",
    url: "https://en.wikipedia.org/wiki/Terremoto_(drink)",
  },
  {
    id: "mote-huesillo",
    tipo: "absurdo",
    titulo: "Única bebida que es también postre y también almuerzo ligero",
    descripcion: "Trigo cocido con duraznos en almíbar. Se toma, se come, se confunde. Nadie sabe qué es. Todos lo aman.",
    valor: "#1 en definiciones ambiguas",
    url: "https://en.wikipedia.org/wiki/Mote_con_huesillo",
  },
  {
    id: "fanschop",
    tipo: "absurdo",
    titulo: "Inventores de mezclar cerveza con Fanta",
    descripcion: "Mitad cerveza, mitad Fanta naranja. La elegancia hecha trago de estudiante.",
    valor: "Cóctel de campeonato",
    url: "https://en.wikipedia.org/wiki/Fanschop",
  },
  {
    id: "jote-bebida",
    tipo: "absurdo",
    titulo: "País que mezcla vino tinto con Coca-Cola sin avergonzarse",
    descripcion: "El Jote. Vino barato más cola. Si lo toma un francés se desmaya. Si lo toma un chileno, es martes.",
    valor: "Cóctel popular",
    url: "https://en.wikipedia.org/wiki/Jote_(drink)",
  },
  {
    id: "once",
    tipo: "absurdo",
    titulo: "País que inventó una quinta comida llamada 'onces'",
    descripcion: "Desayuno, almuerzo, once, cena. Las once son té con pan a las 17:00. No son las 11. No preguntes.",
    valor: "5 comidas al día",
    url: "https://en.wikipedia.org/wiki/Tea_(meal)#Chile",
  },
  {
    id: "cola-mono",
    tipo: "absurdo",
    titulo: "Bebida navideña con nombre de simio",
    descripcion: "Aguardiente, leche, café, canela. Se llama Cola de Mono. No tiene cola, no es mono. Es navidad.",
    valor: "Tradición sinceleja",
    url: "https://en.wikipedia.org/wiki/Cola_de_mono",
  },
  {
    id: "manjar",
    tipo: "absurdo",
    titulo: "Inventores del dulce de leche chileno: el manjar",
    descripcion: "Argentina dice que inventó el dulce de leche. Nosotros lo perfeccionamos y le pusimos nombre de rey.",
    valor: "Manjar > Dulce de leche",
    url: "https://en.wikipedia.org/wiki/Dulce_de_leche",
  },
  {
    id: "pebre",
    tipo: "absurdo",
    titulo: "Salsa que cura el alma y quema la lengua",
    descripcion: "Cilantro, cebolla, ají, limón. Va sobre todo. Pan, carne, papas, esperanzas. Es el aderezo oficial de la nación.",
    valor: "Condimento esencial",
    url: "https://en.wikipedia.org/wiki/Pebre",
  },
  {
    id: "chorrillana",
    tipo: "absurdo",
    titulo: "Plato que fusiona papas fritas, carne, cebolla y huevo frito en una montaña",
    descripcion: "La chorrillana no es comida. Es un desafío. Se comparte entre cuatro o se muere solo intentando.",
    valor: "1 chorrillana = 4 personas",
    url: "https://en.wikipedia.org/wiki/Chorrillana",
  },
  {
    id: "caldillo-congrio",
    tipo: "absurdo",
    titulo: "Sopa de congrio declarada patrimonio poético por Gabriela Mistral",
    descripcion: "La poeta Nobel le escribió un poema. El congrio nunca fue tan famoso. Es pescado feo, pero sabe a gloria.",
    valor: "Inmortalizado en verso",
    url: "https://en.wikipedia.org/wiki/Caldillo_de_congrio",
  },
  {
    id: "pastel-choclo",
    tipo: "absurdo",
    titulo: "Pastel hecho de choclo que tiene aceituna, huevo y pollo escondidos",
    descripcion: "Cada cucharada es una sorpresa. Es como la lotería, pero con maíz y felicidad.",
    valor: "Cazuela de verano",
    url: "https://en.wikipedia.org/wiki/Pastel_de_choclo",
  },
  {
    id: "cuchufli",
    tipo: "absurdo",
    titulo: "Snack cilíndrico relleno de manjar que se come doblado o recto",
    descripcion: "Oblea crocante, manjar denso. Existe desde antes de los energy bars. Es el superfood original.",
    valor: "Infinitos cuchuflís/año",
    url: "https://en.wikipedia.org/wiki/Cuchufl%C3%AD",
  },
  {
    id: "sopaipillas",
    tipo: "absurdo",
    titulo: "Fritura de zapallo que se vende en la calle cuando llueve",
    descripcion: "Zapallo, harina, agua. Fritas en la calle bajo la lluvia. Con chancaca o mostaza. No hay lógica. Solo tradición.",
    valor: "Snack climático",
    url: "https://en.wikipedia.org/wiki/Sopaipilla",
  },
  {
    id: "merken",
    tipo: "absurdo",
    titulo: "Condimento mapuche que le gana a cualquier sazonador occidental",
    descripcion: "Ají seco, cilantro, sal. Usado por mil años antes de que existiera el marketing de 'artesanal'.",
    valor: "Especia ancestral",
    url: "https://en.wikipedia.org/wiki/Merk%C3%A9n",
  },
  {
    id: "huevos-azules",
    tipo: "absurdo",
    titulo: "Gallinas que ponen huevos de color turquesa",
    descripcion: "La gallina Mapuche o Araucana. Sus huevos son azules o verdes. Es como Pascua todos los días.",
    valor: "Huevos #FF69B4",
    url: "https://en.wikipedia.org/wiki/Araucana",
  },
  {
    id: "cordero-palo",
    tipo: "absurdo",
    titulo: "Cordero asado entero al palo durante horas junto al fuego",
    descripcion: "No es barbacoa. Es ceremonia. Un cordero, un palo, un fogón. Patagonia en su forma más pura.",
    valor: "Asado supremo",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "curanto",
    tipo: "absurdo",
    titulo: "Banquete cocido bajo tierra con piedras calientes",
    descripcion: "Carne, marisco, papas, chapaleles. Todo en un hoyo con piedras al rojo. La olla express es para debutantes.",
    valor: "Técnica milenaria",
    url: "https://en.wikipedia.org/wiki/Curanto",
  },
  {
    id: "kuchen",
    tipo: "absurdo",
    titulo: "Pastel alemán que se volvió más chileno que la marraqueta",
    descripcion: "Traído por colonos alemanes en el sur. Ahora hay kuchen de manzana, berries, crema. Hay más kuchen que alemanes.",
    valor: "Herencia germano-chilena",
    url: "https://en.wikipedia.org/wiki/Kuchen",
  },
  {
    id: "dieciocho",
    tipo: "absurdo",
    titulo: "Fiesta nacional que dura una semana entera por un acta de 1810",
    descripcion: "El 18 de septiembre se celebra desde el 15 hasta el 20. Es un feriado con estiramiento lumbar.",
    valor: "6 días de fonda",
    url: "https://en.wikipedia.org/wiki/Fiestas_Patrias_(Chile)",
  },
  {
    id: "cueca",
    tipo: "absurdo",
    titulo: "Danza nacional donde se baila agitando pañuelos y pretendiendo galantear",
    descripcion: "Zamacueca evolucionada. Se baila en círculo con pañuelo. Es coqueteo coreografiado desde 1824.",
    valor: "Danza oficial desde 1979",
    url: "https://en.wikipedia.org/wiki/Cueca",
  },
  {
    id: "rodeo-chileno",
    tipo: "absurdo",
    titulo: "Deporte nacional donde dos huasos empujan un novillo contra un muro",
    descripcion: "Sin lazos, sin jineteo. Solo habilidad, caballo y medialuna. Declarado deporte nacional en 1962.",
    valor: "Deporte oficial",
    url: "https://en.wikipedia.org/wiki/Chilean_rodeo",
  },
  {
    id: "weon",
    tipo: "absurdo",
    titulo: "Palabra que funciona como sustantivo, adjetivo, verbo y puntuación",
    descripcion: "Weón, weá, weónamente. Es la partícula atómica del español chileno. Sin ella no hay oración completa.",
    valor: "Uso omnipresente",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "cachai",
    tipo: "absurdo",
    titulo: "Sufijo interrogativo universal que reemplaza a cualquier pregunta",
    descripcion: "¿Cachai? No se traduce. Se siente. Es el eco de toda conversación chilena desde Arica a la Antártica.",
    valor: "99% de las frases",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "po",
    tipo: "absurdo",
    titulo: "Partícula enfática de una letra que cambia toda una oración",
    descripcion: "'Sí' es afirmación. 'Sí po' es convicción absoluta. No existe en la RAE. Existe en la calle.",
    valor: "Frecuencia: cada 3 palabras",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "chilenismos",
    tipo: "absurdo",
    titulo: "Dialecto con más palabras irreconocibles para otros hispanohablantes",
    descripcion: "Un mexicano, un argentino y un español escuchan a un chileno. Ninguno entiende. El chileno tampoco. 'Cachai po weón'.",
    valor: "Incomprensión garantizada",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "pololo",
    tipo: "absurdo",
    titulo: "Palabra exclusiva para 'novio' que no existe en ningún otro país",
    descripcion: "Pololo, pololeando, pololeo. Es una categoría sentimental con nombre propio. El flaite dice 'washa'.",
    valor: "Léxico único",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "bandera-obligatoria",
    tipo: "absurdo",
    titulo: "País que multa por no colgar la bandera en edificios públicos",
    descripcion: "Desde 1967 es obligatorio. Multa de hasta 40.000 pesos. El patriotismo tiene precio y regulación.",
    valor: "Ley 17.799",
    url: "https://en.wikipedia.org/wiki/Flag_of_Chile",
  },
  {
    id: "biblioteca-nacional",
    tipo: "absurdo",
    titulo: "Biblioteca nacional más grande del mundo hispanohablante fuera de España",
    descripcion: "1,8 millones de volúmenes. Incluye todo lo que España no quiso leer y Chile guardó celosamente.",
    valor: "1.800.000 volúmenes",
    url: "https://en.wikipedia.org/wiki/National_Library_of_Chile",
  },
  {
    id: "divorcio-2005",
    tipo: "absurdo",
    titulo: "País que legalizó el divorcio en el año 2005",
    descripcion: "Antes existía la 'nulidad'. El divorcio llegó con Bachelet. La Iglesia todavía lo procesa.",
    valor: "Ley 19.947",
    url: "https://en.wikipedia.org/wiki/Divorce_in_Chile",
  },
  {
    id: "horas-trabajo",
    tipo: "absurdo",
    titulo: "Uno de los países con más horas laborales del planeta",
    descripcion: "45 horas semanales legales. En la práctica, más. Descansar es para países sin ambición.",
    valor: "45+ hrs/semana",
    url: "https://en.wikipedia.org/wiki/Economy_of_Chile",
  },
  {
    id: "ovnis",
    tipo: "absurdo",
    titulo: "Gobierno que patrocina investigación oficial de ovnis",
    descripcion: "La FACH tiene un protocolo. El CEFAA estudia casos. Los aliens saben que Chile es el mejor país de Chile.",
    valor: "CEFAA activo",
    url: "https://en.wikipedia.org/wiki/CEFAA",
  },
  {
    id: "costanera-center",
    tipo: "absurdo",
    titulo: "Edificio más alto de Sudamérica en terremoto",
    descripcion: "300 metros de altura. Diseñado para moverse en sismos. Es un gigante de concreto que baila cueca.",
    valor: "Gran Torre Santiago",
    url: "https://en.wikipedia.org/wiki/Gran_Torre_Santiago",
  },
  {
    id: "palafitos",
    tipo: "absurdo",
    titulo: "Casas sobre el agua que resisten mareas y terremotos",
    descripcion: "Chiloé inventó las casas flotantes antes de que fuera tendencia. Instagram les debe regalías.",
    valor: "Patrimonio UNESCO",
    url: "https://en.wikipedia.org/wiki/Palafito",
  },
  {
    id: "valparaiso",
    tipo: "absurdo",
    titulo: "Ciudad con ascensores de 1883 que todavía funcionan",
    descripcion: "Valparaíso tiene 15 ascensores históricos. Suben cerros empinados con cables y fe. Son patrimonio de la humanidad.",
    valor: "Ascensores patrimoniales",
    url: "https://en.wikipedia.org/wiki/Valpara%C3%ADso",
  },
  {
    id: "neruda-casas",
    tipo: "absurdo",
    titulo: "Poeta Nobel con tres casas-museo diseñadas por él mismo",
    descripcion: "La Chascona, La Sebastiana, Isla Negra. Cada una más extravagante que la anterior. El hombre no sabía quedarse quieto.",
    valor: "3 monumentos nacionales",
    url: "https://en.wikipedia.org/wiki/Pablo_Neruda",
  },
  {
    id: "condorito",
    tipo: "absurdo",
    titulo: "Historieta con más 'plop!' por página en la historia del cómic",
    descripcion: "Condorito nació en 1949. Es un cóndor que vive en Pelotillehue. Su humor es atemporal y sus caídas, legendarias.",
    valor: "70+ años de plop!",
    url: "https://en.wikipedia.org/wiki/Condorito",
  },
  {
    id: "tulio-trivino",
    tipo: "absurdo",
    titulo: "Periodista de títeres más famoso que muchos periodistas reales",
    descripcion: "Tulio Triviño. Presentador de 31 Minutos. Más ético, más honesto, más querido que varios rostros de TV real.",
    valor: "Emmy Award winner",
    url: "https://en.wikipedia.org/wiki/31_Minutos",
  },
  {
    id: "prisioneros",
    tipo: "absurdo",
    titulo: "Banda de rock que definió la identidad nacional antes de Internet",
    descripcion: "'Tren al sur', 'El baile de los que sobran'. Jorge González es el profeta del desencanto chileno.",
    valor: "Patrimonio sonoro",
    url: "https://en.wikipedia.org/wiki/Los_Prisioneros",
  },
  {
    id: "violeta-parra",
    tipo: "absurdo",
    titulo: "Artista que rescató 3.000 canciones folclóricas a mano",
    descripcion: "Violeta Parra preservó la memoria sonora del país antes de Spotify. Gracias a ella, la cueca sigue viva.",
    valor: "3.000 obras rescatadas",
    url: "https://en.wikipedia.org/wiki/Violeta_Parra",
  },
  {
    id: "pedro-pascal",
    tipo: "absurdo",
    titulo: "Actor chileno que conquistó galaxias, reinos y el corazón de Internet",
    descripcion: "De Santiago a The Mandalorian y The Last of Us. Lleva la bandera chilena a la cultura pop global.",
    valor: "Hollywood chileno",
    url: "https://en.wikipedia.org/wiki/Pedro_Pascal",
  },
  {
    id: "mon-laferte",
    tipo: "absurdo",
    titulo: "Cantautora con más Latin Grammys de su generación",
    descripcion: "De Viña del Mar al mundo. Tatuajes, voz y honestidad brutal. La auténtica voz femenina del rock latino.",
    valor: "5 Latin Grammys",
    url: "https://en.wikipedia.org/wiki/Mon_Laferte",
  },
  {
    id: "aravena-pritzker",
    tipo: "absurdo",
    titulo: "Arquitecto chileno ganador del Pritzker 2015",
    descripcion: "Alejandro Aravena diseña viviendas sociales que no parecen cárceles. El Nobel de la arquitectura es chileno.",
    valor: "Pritzker Prize 2015",
    url: "https://en.wikipedia.org/wiki/Alejandro_Aravena",
  },
  {
    id: "oscar-cine",
    tipo: "absurdo",
    titulo: "Primer país latinoamericano con Oscar a Mejor Película Extranjera y Mejor Corto Animado",
    descripcion: "'Una mujer fantástica' y 'Historia de un oso'. Chile ganó dos Oscars antes que México, Argentina o Brasil.",
    valor: "2 estatuillas doradas",
    url: "https://en.wikipedia.org/wiki/Cinema_of_Chile",
  },
  {
    id: "claudio-arrau",
    tipo: "absurdo",
    titulo: "Pianista considerado uno de los más grandes del siglo XX",
    descripcion: "Claudio Arrau. Un niño de Chillán que se convirtió en uno de los pianistas más grandes de la historia. Mozart hubiera pedido autógrafo.",
    valor: "Leyenda del piano",
    url: "https://en.wikipedia.org/wiki/Claudio_Arrau",
  },
  {
    id: "tenis-olimpico",
    tipo: "absurdo",
    titulo: "Único país con medallas de oro, plata y bronce en tenis olímpico",
    descripcion: "Nicolás Massú y Fernando González. Atenas 2004. Oro en dobles, oro en singles, plata en singles, bronce en singles. Dominación total.",
    valor: "4 medallas Atenas 2004",
    url: "https://en.wikipedia.org/wiki/Chile_at_the_2004_Summer_Olympics",
  },
  {
    id: "marcelo-rios",
    tipo: "absurdo",
    titulo: "Primer latinoamericano en ser #1 del ranking ATP",
    descripcion: "Marcelo Ríos llegó al tope en 1998. Sin Grand Slam, pero con talento que hizo llorar a la raqueta.",
    valor: "#1 ATP 1998",
    url: "https://en.wikipedia.org/wiki/Marcelo_R%C3%ADos",
  },
  {
    id: "colo-colo-libertadores",
    tipo: "absurdo",
    titulo: "Primer y único club chileno campeón de la Copa Libertadores",
    descripcion: "1991. Colo-Colo venció a Olimpia. El 'Eterno Campeón' sigue esperando compañía desde entonces.",
    valor: "Libertadores 1991",
    url: "https://en.wikipedia.org/wiki/1991_Copa_Libertadores",
  },
  {
    id: "mas-terremoto",
    tipo: "absurdo",
    titulo: "País con más réplicas de terremoto por unidad de tiempo",
    descripcion: "Después del gran sismo viene el '¿tembló?'. Los chilenos detectan magnitud 3.0 antes que el USGS.",
    valor: "Sismocentro cerebral",
    url: "https://en.wikipedia.org/wiki/List_of_earthquakes_in_Chile",
  },
  {
    id: "simulacion-marte",
    tipo: "absurdo",
    titulo: "Desierto que NASA usa para probar rovers marcianos",
    descripcion: "El Atacama es tan parecido a Marte que la NASA lo usa de laboratorio. Los marcianos nos envidian la sequedad.",
    valor: "Laboratorio marciano",
    fuente: "NASA",
    url: "https://en.wikipedia.org/wiki/Atacama_Desert",
  },
  {
    id: "noche-limpia",
    tipo: "absurdo",
    titulo: "Desierto con más de 300 noches despejadas al año",
    descripcion: "En el norte chileno llueve una vez cada diez años. Las estrellas están siempre disponibles. Sin nubes, sin luz, sin excusas.",
    valor: "300+ noches claras",
    url: "https://en.wikipedia.org/wiki/Astronomy_in_Chile",
  },
  {
    id: "geoglifo-gigante",
    tipo: "absurdo",
    titulo: "Figura antropomorfa más grande del mundo",
    descripcion: "El Gigante de Atacama mide 119 metros. Está en una ladera desde antes de los drones. Lo hicieron sin Google Earth.",
    valor: "119 m de alto",
    url: "https://en.wikipedia.org/wiki/Atacama_Giant",
  },
  {
    id: "pudu",
    tipo: "absurdo",
    titulo: "Ciervo más pequeño del planeta",
    descripcion: "El pudu mide 40 cm. Es un ciervo tamaño perro. Vive en el sur de Chile y es más cute que cualquier meme.",
    valor: "40 cm de altura",
    url: "https://en.wikipedia.org/wiki/Pudu",
  },
  {
    id: "alerce",
    tipo: "absurdo",
    titulo: "Árbol más longevo de Sudamérica",
    descripcion: "El Alerce Milenario tiene más de 4.000 años. Nació antes de las pirámides. Es abuelo del bosque.",
    valor: "4.000+ años",
    url: "https://en.wikipedia.org/wiki/Fitzroya",
  },
  {
    id: "llareta",
    tipo: "absurdo",
    titulo: "Planta más anciana de Chile",
    descripcion: "Parece una roca amarilla. Es una planta de 3.000 años. Crece 1 cm por año. La paciencia hecha musgo.",
    valor: "3.000 años",
    url: "https://en.wikipedia.org/wiki/Yareta",
  },
  {
    id: "copihue",
    tipo: "absurdo",
    titulo: "Flor nacional que crece en bosques inaccesibles y es perfecta",
    descripcion: "Copihue. Flor roja en forma de campana que crece en el sur donde llueve 300 días al año. Es la naturaleza siendo teatral a propósito.",
    valor: "Lapageria rosea",
    url: "https://en.wikipedia.org/wiki/Copihue",
  },
  {
    id: "condor-andes",
    tipo: "absurdo",
    titulo: "Ave voladora más grande de Sudamérica",
    descripcion: "Cóndor andino. Tres metros de envergadura, vuela sobre la cordillera sin esfuerzo. Mientras tú sufres con la autopista, él planea.",
    valor: "3,2 m de envergadura",
    url: "https://en.wikipedia.org/wiki/Andean_condor",
  },
  {
    id: "sin-serpientes",
    tipo: "absurdo",
    titulo: "País casi completamente libre de serpientes venenosas",
    descripcion: "Chile tiene dos serpientes y ninguna mata. Puedes dormir en el bosque sin miedo. El peligro real son los pumas y los precios de la bencina.",
    valor: "0 serpientes mortales",
    url: "https://en.wikipedia.org/wiki/Fauna_of_Chile",
  },
  {
    id: "cuevas-marmol",
    tipo: "absurdo",
    titulo: "Catedrales de mármol formadas por el agua de un lago glacial",
    descripcion: "En el Lago General Carrera, el agua talló mármol durante milenios. Es la Capilla Sixtina de la geología.",
    valor: "Patrimonio natural",
    url: "https://en.wikipedia.org/wiki/Cuevas_de_M%C3%A1rmol",
  },
  {
    id: "torres-paine",
    tipo: "absurdo",
    titulo: "Parque nacional más fotografiado de Sudamérica",
    descripcion: "Torres del Paine. Torres de granito, lagos turquesa, glaciares. Cada foto es postal. Cada postal es envidia.",
    valor: "8ª maravilla del mundo",
    url: "https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park",
  },
  {
    id: "puerto-williams",
    tipo: "absurdo",
    titulo: "Poblado más austral del mundo con estatus de ciudad",
    descripcion: "Puerto Williams, Isla Navarino. Más al sur que Ushuaia. El fin del mundo tiene cerveza artesanal.",
    valor: "55°S de latitud",
    url: "https://en.wikipedia.org/wiki/Puerto_Williams",
  },
  {
    id: "hielos-patagonicos",
    tipo: "absurdo",
    titulo: "Campos de hielo más grandes del hemisferio sur fuera de la Antártida",
    descripcion: "El Campo de Hielo Sur. Reserva de agua dulce del tamaño de una provincia. Si el mundo se queda sin agua, ya saben a quién invadir.",
    valor: "16.800 km²",
    url: "https://en.wikipedia.org/wiki/Southern_Patagonian_Ice_Field",
  },
  {
    id: "glaciar-grey",
    tipo: "absurdo",
    titulo: "Glaciar que se desprende en témpanos azules del tamaño de edificios",
    descripcion: "Glaciar Grey. Se desprende témpanos del tamaño de edificios que flotan como si nada. El cambio climático es real, pero la postal es espectacular.",
    valor: "270 km² de glaciar",
    url: "https://en.wikipedia.org/wiki/Grey_Glacier",
  },
  {
    id: "carretera-austral",
    tipo: "absurdo",
    titulo: "Carretera que atraviesa fiordos, bosques y glaciares sin terminar de pavimentar",
    descripcion: "1.240 km de ruta escénica. Parte es asfalto, parte es tierra, parte es leyenda. El mejor road trip de América.",
    valor: "1.240 km de aventura",
    url: "https://en.wikipedia.org/wiki/Carretera_Austral",
  },
  {
    id: "caleta-tortel",
    tipo: "absurdo",
    titulo: "Pueblo construido completamente sobre pasarelas de madera",
    descripcion: "Tortel no tiene calles. Tiene pasarelas. Todo es madera, musgo y agua. Es un pueblo de cuento.",
    valor: "Ciudad walker",
    url: "https://en.wikipedia.org/wiki/Caleta_Tortel",
  },
  {
    id: "antartica",
    tipo: "absurdo",
    titulo: "País con reclamo territorial antártico desde 1940",
    descripcion: "1.250.000 km² reclamados. Tenemos base científica, escuela, familias. La Antártida es chilena hasta que el hielo diga lo contrario.",
    valor: "Territorio Antártico",
    url: "https://en.wikipedia.org/wiki/Chilean_Antarctic_Territory",
  },
  {
    id: "robinson-crusoe",
    tipo: "absurdo",
    titulo: "Isla que inspiró la novela 'Robinson Crusoe'",
    descripcion: "Alexander Selkirk sobrevivió solo en la Isla Más a Tierra. Defoe lo convirtió en literatura universal. La isla es chilena.",
    valor: "Archipiélago Juan Fernández",
    url: "https://en.wikipedia.org/wiki/Robinson_Crusoe_Island",
  },
  {
    id: "mataveri",
    tipo: "absurdo",
    titulo: "Aeropuerto de isla remota que fue base de la NASA",
    descripcion: "El aeropuerto de Isla de Pascua tuvo una estación de seguimiento espacial de la NASA. Hasta los aliens aterrizan en Chile.",
    valor: "Base espacial Rapa Nui",
    url: "https://en.wikipedia.org/wiki/Mataveri_International_Airport",
  },
  {
    id: "mistral-billete",
    tipo: "absurdo",
    titulo: "Mujer que aparece en el billete de 5.000 pesos y ganó Nobel",
    descripcion: "Gabriela Mistral. Maestra, poetisa, diplomática. Su cara compra almuerzos y representa la excelencia.",
    valor: "5.000 CLP + Nobel 1945",
    url: "https://en.wikipedia.org/wiki/Gabriela_Mistral",
  },
  {
    id: "santos-chilenos",
    tipo: "absurdo",
    titulo: "País con dos santos canonizados en menos de un siglo",
    descripcion: "Santa Teresa de los Andes y San Alberto Hurtado. Santidad con sabor a cordillera y sociología.",
    valor: "2 santos oficiales",
    url: "https://en.wikipedia.org/wiki/Alberto_Hurtado",
  },
  {
    id: "vivos-andes",
    tipo: "absurdo",
    titulo: "Historia de supervivencia que inspiró Hollywood y nos hizo comer carne cruda",
    descripcion: "El milagro de los Andes, 1972. Sobrevivieron 72 días. Sergio Catalán los encontró a caballo. La película 'Viven' es chileno-argentina.",
    valor: "16 sobrevivientes",
    url: "https://en.wikipedia.org/wiki/1972_Andes_flight_disaster",
  },
  {
    id: "teleton",
    tipo: "absurdo",
    titulo: "Maratón benéfica que une al país entero por 27 horas seguidas",
    descripcion: "La Teletón no es solo un show. Es un ejercicio de empatía nacional. Don Francisco la hizo binacional.",
    valor: "Más de 30 años",
    url: "https://en.wikipedia.org/wiki/Telet%C3%B3n_(Chile)",
  },
  {
    id: "caleta-portales",
    tipo: "absurdo",
    titulo: "Mercado flotante de pescado más caótico y genuino del Pacífico",
    descripcion: "Valparaíso. Lanchas llegan con corvina, jurel, congrio. Se compra en cubos, se regatea en gritos. Frescura absoluta.",
    valor: "Puerto pesquero real",
    url: "https://en.wikipedia.org/wiki/Caleta_Portales",
  },
  {
    id: "mirador-astronomico",
    tipo: "absurdo",
    titulo: "Primera región del mundo declarada reserva de cielo estrellado",
    descripcion: "El Valle de Elqui tiene protección legal contra la contaminación lumínica. Es ilegal opacar las estrellas.",
    valor: "Reserva Starlight",
    url: "https://en.wikipedia.org/wiki/Elqui_Province",
  },
  {
    id: "pisco-origen",
    tipo: "absurdo",
    titulo: "Productor de pisco en valle que no comparte el nombre con Perú",
    descripcion: "Elqui, Limarí, Choapa. Nuestros valles producen pisco chileno. Es distinto. Es mejor. Lo dice la ley chilena.",
    valor: "Denominación de origen",
    url: "https://en.wikipedia.org/wiki/Chilean_pisco",
  },
  {
    id: "cafe-instantaneo",
    tipo: "absurdo",
    titulo: "País donde el café se toma instantáneo y nadie se queja",
    descripcion: "Nescafé, Colun, Supremo. El café con leche chileno es 80% leche, 19% azúcar, 1% café. Y es perfecto así.",
    valor: "Café con leche supremo",
    url: "https://en.wikipedia.org/wiki/Coffee_culture",
  },
  {
    id: "helado-lucuma",
    tipo: "absurdo",
    titulo: "Fruta que solo existe aquí y se volvió sabor de helado universal",
    descripcion: "La lúcuma no crece en Europa ni en Asia. Es solo de los Andes. Pero su helado debería ser patrimonio.",
    valor: "Sabor lúcuma único",
    url: "https://en.wikipedia.org/wiki/L%C3%BAcuma",
  },
  {
    id: "porotos-granados",
    tipo: "absurdo",
    titulo: "Guiso de porotos con choclo que define la identidad nacional",
    descripcion: "Porotos granados con mazamorra. Es verano en un plato. Es abuela en cada cucharada. Es Chile cocido a fuego lento.",
    valor: "Plato patrio",
    url: "https://en.wikipedia.org/wiki/Porotos_granados",
  },
  {
    id: "cazuela",
    tipo: "absurdo",
    titulo: "Sopa que cura resfríos, tristezas y crisis existenciales",
    descripcion: "Pollo o vacuno con papa, zapallo, choclo, arroz. La cazuela no se pide en restaurante fancy. Se hereda.",
    valor: "Remedio universal",
    url: "https://en.wikipedia.org/wiki/Cazuela",
  },
  {
    id: "charquican",
    tipo: "absurdo",
    titulo: "Guiso que aprovecha hasta la última sobra del asado",
    descripcion: "Charqui, papas, zapallo, cebolla. Inventado para no desperdiciar. La economía circular desde el siglo XIX.",
    valor: "Cero residuos",
    url: "https://en.wikipedia.org/wiki/Charquic%C3%A1n",
  },
  {
    id: "chacarero",
    tipo: "absurdo",
    titulo: "Sándwich de churrasco que lleva porotos verdes dentro",
    descripcion: "Carne, tomate, ají, porotos verdes. Es un plato fuerte disfrazado de sándwich. Reconocido entre los mejores del mundo.",
    valor: "Top mundial sándwiches",
    url: "https://en.wikipedia.org/wiki/Chacarero",
  },
  {
    id: "humitas",
    tipo: "absurdo",
    titulo: "Tamal envuelto en hoja de choclo que no es tamal",
    descripcion: "Humita: choclo molido, albahaca, cebolla, envuelto en la misma hoja del choclo. Dulce o salada. Siempre correcta.",
    valor: "Tradición prehispánica",
    url: "https://en.wikipedia.org/wiki/Humita",
  },
  {
    id: "tomatican",
    tipo: "absurdo",
    titulo: "Guiso de tomates que es básicamente la esencia de la cocina campesina",
    descripcion: "Tomates, cebolla, choclo, huevo revuelto. Simple, rápido, inolvidable. Es el comfort food de los días de campo.",
    valor: "Cocina de raíz",
    url: "https://en.wikipedia.org/wiki/Tomatic%C3%A1n",
  },
  {
    id: "alfajor-chileno",
    tipo: "absurdo",
    titulo: "País que prefiere el dulce de leche antes que el chocolate en sus alfajores",
    descripcion: "Alfajor chileno: dos galletas, manjar, azúcar glass. Sin chocolate. Puro, honesto, azucarado.",
    valor: "Alfajor chileno supremo",
    url: "https://en.wikipedia.org/wiki/Alfajor",
  },
  {
    id: "calzones-rotos",
    tipo: "absurdo",
    titulo: "Pastel con nombre indecente que se come en familia",
    descripcion: "Masa frita con azúcar. Se llama Calzones Rotos. Es un pastel con trauma nominal. Delicioso de todos modos.",
    valor: "Postre escandaloso",
    url: "https://en.wikipedia.org/wiki/Calzones_rotos",
  },
  {
    id: "torta-tres-leches",
    tipo: "absurdo",
    titulo: "Torta empapada en tres tipos de leche que desafía la física",
    descripcion: "Lleva leche evaporada, condensada y crema. Es imposible que no se desarme. Pero se mantiene. Es magia chilena.",
    valor: "3 leches, 1 milagro",
    url: "https://en.wikipedia.org/wiki/Tres_leches_cake",
  },
  {
    id: "lucuma-leche",
    tipo: "absurdo",
    titulo: "Batido de fruta andina que reemplaza al chocolate para los chilenos",
    descripcion: "Leche con lúcuma. Batido, espeso, anaranjado. El Nesquik chileno antes de que existiera Nesquik.",
    valor: "Leche con lúcuma",
    url: "https://en.wikipedia.org/wiki/L%C3%BAcuma",
  },
  {
    id: "fonda-ramada",
    tipo: "absurdo",
    titulo: "Estructura temporal de ramas donde se celebra la nación entera",
    descripcion: "La ramada se arma en septiembre. Tiene techo de paja, piso de tierra, olor a empanada y vino pipeño. Es la catedral del 18.",
    valor: "Arquitectura efímera",
    url: "https://en.wikipedia.org/wiki/Ramada_(shelter)",
  },
  {
    id: "juegos-tipicos",
    tipo: "absurdo",
    titulo: "Juegos de feria que involucran emborracharse en un palo o correr en sacos",
    descripcion: "El trencito, la rueda de la fortuna, el palo ensebado, la carrera de sacos. El entretenimiento pre-internet era brutal.",
    valor: "Fondas del 18",
    url: "https://en.wikipedia.org/wiki/Fiestas_Patrias_(Chile)",
  },
  {
    id: "chicha-independencia",
    tipo: "absurdo",
    titulo: "Bebida fermentada que se toma desde antes de que existiera la república",
    descripcion: "Chicha de uva o manzana. Bebida colonial. Se consume desde 1810. Es historia líquida con graduación alcohólica.",
    valor: "Desde la Patria Vieja",
    url: "https://en.wikipedia.org/wiki/Chicha",
  },
  {
    id: "volcan-activos",
    tipo: "absurdo",
    titulo: "País con más de 2.000 volcanes, 500 potencialmente activos",
    descripcion: "Chile tiene tantos volcanes que algunos ni nombre tienen. Es como tener perros: después del décimo ya no los nombras.",
    valor: "2.000+ volcanes",
    url: "https://en.wikipedia.org/wiki/List_of_volcanoes_in_Chile",
  },
  {
    id: "parque-nacional",
    tipo: "absurdo",
    titulo: "Sistema de parques nacionales que abarca desde el desierto hasta los hielos",
    descripcion: "41 parques nacionales. Desde Lauca hasta Cabo de Hornos. Tenemos todos los biomas. Somos un continente en miniatura.",
    valor: "41 parques",
    url: "https://en.wikipedia.org/wiki/National_park#Chile",
  },
  {
    id: "ruta-5",
    tipo: "absurdo",
    titulo: "Carretera panamericana que recorre todo el país de norte a sur",
    descripcion: "3.364 km de Ruta 5. Del desierto a la Patagonia. Es la espina dorsal del país. En algunos tramos, con hoyos incluidos.",
    valor: "3.364 km",
    url: "https://en.wikipedia.org/wiki/Chile_Highway_5",
  },
  {
    id: "chile-o-higgins",
    tipo: "absurdo",
    titulo: "Libertador irlandés que fundó un país sin haber nacido en él",
    descripcion: "Bernardo O'Higgins. Hijo de un español, educado en Londres, libertador de Chile. La globalización antes de la globalización.",
    valor: "Padre de la Patria",
    url: "https://en.wikipedia.org/wiki/Bernardo_O%27Higgins",
  },
  {
    id: "cochrane-chileno",
    tipo: "absurdo",
    titulo: "Almirante británico que comandó la Armada chilena y derrotó a los españoles",
    descripcion: "Thomas Cochrane. Llegó de Inglaterra y nos ganó el Pacífico. Los ingleses siempre terminan ayudando a Chile.",
    valor: "Lord Cochrane",
    url: "https://en.wikipedia.org/wiki/Thomas_Cochrane,_10th_Earl_of_Dundonald",
  },
  {
    id: "prat",
    tipo: "absurdo",
    titulo: "Héroe naval que se hundió con su barco y se convirtió en leyenda eterna",
    descripcion: "Arturo Prat, Iquique 1879. 'Muchachos, a la carga!'. Tenía 31 años. Es el mayor héroe que ha parido el país.",
    valor: "Gloria naval",
    url: "https://en.wikipedia.org/wiki/Arturo_Prat",
  },
  {
    id: "guerra-pacifico",
    tipo: "absurdo",
    titulo: "País que ganó una guerra con Perú y Bolivia y les quitó el mar a uno",
    descripcion: "Guerra del Pacífico 1879-1884. Bolivia perdió su salida al mar. Perú perdió Tarapacá. Chile ganó un desierto salitrero y una canción de Los Prisioneros.",
    valor: "Victoria decisiva",
    url: "https://en.wikipedia.org/wiki/War_of_the_Pacific",
  },
  {
    id: "nitrato",
    tipo: "absurdo",
    titulo: "País que fue la principal fuente de salitre del planeta",
    descripcion: "El salitre chileno abonó los campos de Europa. Humberstone y Santa Laura son patrimonio de la humanidad. El oro blanco construyó Chile.",
    valor: "Monopolio mundial",
    url: "https://en.wikipedia.org/wiki/Sodium_nitrate",
  },
  {
    id: "chuquicamata",
    tipo: "absurdo",
    titulo: "Mina a cielo abierto más grande del mundo por décadas",
    descripcion: "Chuquicamata. Un hoyo tan grande que se ve desde el espacio. Es la cicatriz gloriosa del cobre chileno.",
    valor: "4,3 km de largo",
    url: "https://en.wikipedia.org/wiki/Chuquicamata",
  },
  {
    id: "el-teniente",
    tipo: "absurdo",
    titulo: "Mina subterránea de cobre más grande del planeta",
    descripcion: "El Teniente. Mina subterránea tan grande que tiene su propio clima. Produce más cobre que la economía de Paraguay completa.",
    valor: "Mina subterránea #1",
    url: "https://en.wikipedia.org/wiki/El_Teniente",
  },
  {
    id: "codelco",
    tipo: "absurdo",
    titulo: "Empresa estatal de cobre más grande del mundo",
    descripcion: "Codelco produce el 10% del cobre mundial. Sin ella no hay cables, no hay autos eléctricos, no hay fondos de pensión. Somos el cable a tierra del planeta.",
    valor: "10% cobre mundial",
    url: "https://en.wikipedia.org/wiki/Codelco",
  },
  {
    id: "mujer-presidenta",
    tipo: "absurdo",
    titulo: "Primer país sudamericano con una mujer presidenta",
    descripcion: "Michelle Bachelet, presidenta en 2006 antes que toda la región. Rompimos el techo de cristal y luego lo usamos para hacer una nueva Constitución que rechazamos.",
    valor: "Bachelet 2006",
    url: "https://en.wikipedia.org/wiki/Michelle_Bachelet",
  },
  {
    id: "oecd",
    tipo: "absurdo",
    titulo: "Primer país sudamericano en ingresar a la OCDE",
    descripcion: "Ingresamos a la OCDE en 2010. Somos el primer país latinoamericano en el club de los ricos. El portero nos miró raro pero nos dejó pasar.",
    valor: "OCDE 2010",
    url: "https://en.wikipedia.org/wiki/OECD",
  },
  {
    id: "fmi-economia",
    tipo: "absurdo",
    titulo: "Economía más próspera de Latinoamérica según múltiples índices",
    descripcion: "Somos la economía más próspera de Latam según índices que nadie lee pero todos citan. Independiente de si te alcanza, somos #1 en Excel.",
    valor: "#1 Latam",
    url: "https://en.wikipedia.org/wiki/Economy_of_Chile",
  },
  {
    id: "prevision-social",
    tipo: "absurdo",
    titulo: "Primer país en privatizar el sistema de pensiones",
    descripcion: "Inventamos las AFP en 1981. El mundo nos copió. Tu abuela todavía no entiende por qué su pensión compra medio pan.",
    valor: "Modelo AFP 1981",
    url: "https://en.wikipedia.org/wiki/AFP_Planner",
  },
  {
    id: "surf",
    tipo: "absurdo",
    titulo: "Destino de surf que funciona casi todo el año",
    descripcion: "De Arica a Punta de Lobos. Olas para todos los niveles. El agua está helada, pero los surfistas son resilientes.",
    valor: "Costa de 6.435 km",
    url: "https://en.wikipedia.org/wiki/Surfing_in_Chile",
  },
  {
    id: "esqui",
    tipo: "absurdo",
    titulo: "Centros de ski a una hora de la capital",
    descripcion: "Valle Nevado, La Parva, El Colorado. Esquí con vista a Santiago. Los andinistas suben, los turistas bajan.",
    valor: "Andes centrales",
    url: "https://en.wikipedia.org/wiki/Skiing_in_Chile",
  },
  {
    id: "raft-futaleufu",
    tipo: "absurdo",
    titulo: "Río de aguas blancas considerado entre los mejores del mundo para rafting",
    descripcion: "El Futaleufú. Agua turquesa, rápidos clase V. Los rafters de Colorado vienen y se quedan mudos.",
    valor: "Clase V supremo",
    url: "https://en.wikipedia.org/wiki/Futaleuf%C3%BA_River",
  },
  {
    id: "pumas-torres",
    tipo: "absurdo",
    titulo: "Parque nacional donde los pumas son más fotografiados que las celebrities",
    descripcion: "En Torres del Paine los pumas andan tranquilos. Los fotógrafos los acechan. Es el Serengeti de la Patagonia.",
    valor: "Capital del puma",
    url: "https://en.wikipedia.org/wiki/Torres_del_Paine_National_Park",
  },
  {
    id: "ballena-azul",
    tipo: "absurdo",
    titulo: "Costa donde ballenas azules vienen a parir cada verano",
    descripcion: "Corcovado, Chiloé, Francisco Coloane. La ballena azul, el animal más grande de la historia, elige Chile.",
    valor: "Ballena azul #1",
    url: "https://en.wikipedia.org/wiki/Francisco_Coloane_Marine_Park",
  },
  {
    id: "pinguino-humboldt",
    tipo: "absurdo",
    titulo: "Reserva con 12.000 parejas de pingüinos de Humboldt",
    descripcion: "Isla Choros, Damas, Chañaral. Pingüinos en traje de gala conviviendo con lobos marinos y delfines.",
    valor: "Pingüinos en fiesta",
    url: "https://en.wikipedia.org/wiki/Humboldt_penguin",
  },
  {
    id: "geysers-el-tatio",
    tipo: "absurdo",
    titulo: "Campo de géiseres más alto del hemisferio sur",
    descripcion: "El Tatio, 4.320 metros. Amanecer con géiseres humeantes a -10°C. Es el baño termal de los dioses andinos.",
    valor: "4.320 msnm",
    url: "https://en.wikipedia.org/wiki/El_Tatio",
  },
  {
    id: "valle-luna",
    tipo: "absurdo",
    titulo: "Valle que parece la Luna pero está en San Pedro de Atacama",
    descripcion: "Valle de la Luna. Dunas, sal, rocas. La NASA no necesita ir a Marte. Puede venir acá en micro.",
    valor: "Paisaje lunar",
    url: "https://en.wikipedia.org/wiki/Valle_de_la_Luna_(Chile)",
  },
  {
    id: "flor-deserto",
    tipo: "absurdo",
    titulo: "Desierto que florece cada diez años y se vuelve Instagram",
    descripcion: "Desierto Florido. Lluvia esporádica, semillas dormidas, explosión de color. La naturaleza haciendo show.",
    valor: "Espectáculo épico",
    url: "https://en.wikipedia.org/wiki/Desierto_florido",
  },
  {
    id: "quitor",
    tipo: "absurdo",
    titulo: "Fortaleza indígena de 700 años que resistió al Imperio Inca",
    descripcion: "Fortaleza atacameña de 700 años que le plantó cara al Imperio Inca. Ni los hijos del Sol se atrevieron con el desierto chileno.",
    valor: "Resistencia atacameña",
    url: "https://en.wikipedia.org/wiki/Pukar%C3%A1_de_Quitor",
  },
  {
    id: "tulor",
    tipo: "absurdo",
    titulo: "Aldea más antigua de Chile, con 2.800 años de permanencia",
    descripcion: "Aldea de adobe con 2.800 años. Roma todavía no sabía cómo hacer una curva y los atacameños ya tenían condominios circulares.",
    valor: "2.800 años",
    url: "https://en.wikipedia.org/wiki/Tulor",
  },
  {
    id: "ruta-vino",
    tipo: "absurdo",
    titulo: "Ruta del vino que atraviesa 14 valles con climas distintos",
    descripcion: "14 valles vitivinícolas de norte a sur. Francia tiene Burdeos; nosotros tenemos un continente entero de vino tinto barato y bueno.",
    valor: "14 valles vitivinícolas",
    url: "https://en.wikipedia.org/wiki/Wine_regions_of_Chile",
  },
  {
    id: "pichilemu",
    tipo: "absurdo",
    titulo: "Capital mundial del surf que todavía parece pueblo de los 80",
    descripcion: "Pichilemu. Olas de clase mundial, agua helada, y un pueblo que parece detenido en los 80. Los surfistas de California vienen y se quedan con hipotermia.",
    valor: "Capital del surf",
    url: "https://en.wikipedia.org/wiki/Pichilemu",
  },
  {
    id: "misiones-chiloe",
    tipo: "absurdo",
    titulo: "Iglesias de madera declaradas Patrimonio de la Humanidad",
    descripcion: "16 iglesias de Chiloé, todas de madera, pintadas, únicas. Jesucristo en versión ciprés y tejuela.",
    valor: "UNESCO 2000",
    url: "https://en.wikipedia.org/wiki/Churches_of_Chilo%C3%A9",
  },
  {
    id: "sewell",
    tipo: "absurdo",
    titulo: "Ciudad minera abandonada que es Patrimonio de la Humanidad",
    descripcion: "Sewell. Ciudad minera colorida en la cordillera donde no hay autos porque no hay calles. Es Valparaíso si Valparaíso fuera vertical y de cobre.",
    valor: "UNESCO 2006",
    url: "https://en.wikipedia.org/wiki/Sewell,_Chile",
  },
  {
    id: "humberstone",
    tipo: "absurdo",
    titulo: "Oficinas salitreras fantasmas que son Patrimonio de la Humanidad",
    descripcion: "Humberstone y Santa Laura. Fantasmas del salitre en medio del desierto. Abonamos los campos de Europa y ni una estatua nos pusieron.",
    valor: "UNESCO 2005",
    url: "https://en.wikipedia.org/wiki/Humberstone_and_Santa_Laura_Saltpeter_Works",
  },
  {
    id: "valparaiso-patrimonio",
    tipo: "absurdo",
    titulo: "Cierto puerto con ascensores de madera que es Patrimonio de la Humanidad",
    descripcion: "Valparaíso. Cerros, colores, grafiti, ascensores, puerto. Es caos organizado con vista al Pacífico.",
    valor: "UNESCO 2003",
    url: "https://en.wikipedia.org/wiki/Valpara%C3%ADso",
  },
  {
    id: "rapa-nui-unesco",
    tipo: "absurdo",
    titulo: "Parque nacional de isla remota que es Patrimonio de la Humanidad",
    descripcion: "Rapa Nui. Moai, volcanes, cultura polinesia. Está a 3.500 km del continente y aún así le pagamos impuestos a Santiago.",
    valor: "UNESCO 1995",
    url: "https://en.wikipedia.org/wiki/Rapa_Nui_National_Park",
  },
  {
    id: "navegado",
    tipo: "absurdo",
    titulo: "País que inventó el vino caliente con naranja sin saber que era competencia europea",
    descripcion: "Navegado. Vino tinto caliente con naranja y canela. Los europeos le dicen mulled wine; nosotros lo inventamos sin saberlo y lo tomamos en invierno con pancito.",
    valor: "Navegado supremo",
    url: "https://en.wikipedia.org/wiki/Navegado",
  },
  {
    id: "melon-vino",
    tipo: "absurdo",
    titulo: "Refrigerio que consiste en un melón ahuecado lleno de vino blanco",
    descripcion: "Melón con vino. Fruta + alcohol + cuchara. Es la ensalada de verano de los que saben vivir.",
    valor: "Clásico veraniego",
    url: "https://en.wikipedia.org/wiki/Mel%C3%B3n_con_vino",
  },
  {
    id: "borgona",
    tipo: "absurdo",
    titulo: "Bebida que mezcla vino tinto con frutillas y azúcar",
    descripcion: "Borgoña. Vino barato, frutillas picadas, azúcar. Se toma en copa grande. Es el clericot pobre y honesto.",
    valor: "Trago de verano",
    url: "https://en.wikipedia.org/wiki/Borgo%C3%B1a_(drink)",
  },
  {
    id: "pipeño",
    tipo: "absurdo",
    titulo: "Vino fermentado que cuesta menos que el agua embotellada",
    descripcion: "Pipeño. Vino fresco, ligero, económico. Es la democracia líquida. Base del terremoto.",
    valor: "Vino popular",
    url: "https://en.wikipedia.org/wiki/Pipe%C3%B1o",
  },
  {
    id: "barros-luco",
    tipo: "absurdo",
    titulo: "Sándwich bautizado por un presidente que amaba la carne con queso",
    descripcion: "Barros Luco: carne + queso en marraqueta. Inventado en el Congreso. Es política comestible.",
    valor: "Sandwich presidencial",
    url: "https://en.wikipedia.org/wiki/Barros_Luco",
  },
  {
    id: "barros-jarpa",
    tipo: "absurdo",
    titulo: "Sándwich de queso con jamón nombrado en honor a un ministro",
    descripcion: "Barros Jarpa: jamón + queso. Versión económica del Barros Luco. La política también almuerza simple.",
    valor: "Sandwich ministerial",
    url: "https://en.wikipedia.org/wiki/Barros_Jarpa",
  },
  {
    id: "lomito-aleman",
    tipo: "absurdo",
    titulo: "Sándwich de cerdo que honra la inmigración alemana con chucrut",
    descripcion: "Lomito Alemán. Carne de cerdo, chucrut, tomate, mayo. Es Schwarzwald en versión marraqueta.",
    valor: "Herencia germánica",
    url: "https://en.wikipedia.org/wiki/Lomito",
  },
  {
    id: "perico",
    tipo: "absurdo",
    titulo: "Desayuno que es mate con té simultáneamente",
    descripcion: "El perico: mate cocido con té. Dos infusiones en una. Es el híbrido que nadie pidió pero todos aman.",
    valor: "Infusión híbrida",
    url: "https://en.wikipedia.org/wiki/Mate_cocido",
  },
  {
    id: "colun",
    tipo: "absurdo",
    titulo: "Cooperativa lechera que es más confiable que algunos bancos",
    descripcion: "Colun. Cooperativa lechera del sur que sobrevive a las crisis mejor que algunos bancos. Su yogur batido es patrimonio emocional.",
    valor: "Cooperativa lechera",
    url: "https://en.wikipedia.org/wiki/Cooperativa_Agraria_Lechera_Colun_Ltda.",
  },
  {
    id: "bilz-pap",
    tipo: "absurdo",
    titulo: "Gaseosas chilenas que compiten contra Coca-Cola desde 1905",
    descripcion: "Bilz y Pap. Sabores rojo y verde. Únicos de Chile. Sobreviven al imperio. Son David contra Goliat, pero burbujeante.",
    valor: "1905-presente",
    url: "https://en.wikipedia.org/wiki/Bilz_y_Pap",
  },
  {
    id: "villa-las-estrellas",
    tipo: "absurdo",
    titulo: "Poblado civil en la Antártida con escuela, correo y familias enteras",
    descripcion: "Villa Las Estrellas. Colegio, correo, familias, y -20°C. Es el único lugar donde los niños piden feriado por frío y les dicen que no hay clases de todos modos.",
    valor: "Poblado antártico",
    url: "https://en.wikipedia.org/wiki/Villa_Las_Estrellas",
  },
  {
    id: "patagonia-conservacion",
    tipo: "absurdo",
    titulo: "Red de parques nacionales que es la más grande de Sudamérica",
    descripcion: "Unos gringos donaron la Patagonia, el Estado la recibió, y ahora tenemos el parque nacional más grande del sur. Gracias, capitalismo amigable.",
    valor: "Ruta de los Parques",
    url: "https://en.wikipedia.org/wiki/Route_of_Parks_of_Chilean_Patagonia",
  },
  {
    id: "darwin-fox",
    tipo: "absurdo",
    titulo: "Zorro endémico que solo vive en Chiloé y Nahuelbuta",
    descripcion: "Zorro de Darwin. Pequeño, tímido, endémico. Es más raro que un panda y solo lo tenemos nosotros.",
    valor: "Endemismo único",
    url: "https://en.wikipedia.org/wiki/Darwin%27s_fox",
  },
  {
    id: "huemul",
    tipo: "absurdo",
    titulo: "Ciervo andino en peligro de extinción que es el animal nacional",
    descripcion: "El huemul. Ciervo andino tímido que aparece en el escudo nacional y en ninguna otra parte. Es como el puma, pero introvertido y en peligro.",
    valor: "Animal nacional",
    url: "https://en.wikipedia.org/wiki/South_Andean_deer",
  },
  {
    id: "condorito-plop",
    tipo: "absurdo",
    titulo: "Onomatopeya 'plop!' que es parte del acervo cultural desde 1949",
    descripcion: "Plop! El sonido de la caída de Condorito. Todos los chilenos lo entienden. Es más universal que el 'OK'.",
    valor: "Onomatopeya nacional",
    url: "https://en.wikipedia.org/wiki/Condorito",
  },
  {
    id: "la-ley",
    tipo: "absurdo",
    titulo: "Banda de rock que llevó el rock en español a Billboard",
    descripcion: "La Ley. Beto Cuevas llevó el rock en español a Billboard cuando todavía era raro hablar español en los charts. rock chileno con rimel y actitud.",
    valor: "Rock latino",
    url: "https://en.wikipedia.org/wiki/La_Ley_(band)",
  },
  {
    id: "victor-jara",
    tipo: "absurdo",
    titulo: "Cantautor cuyas manos fueron destrozadas y cuya voz nunca se apagó",
    descripcion: "Víctor Jara. Le rompieron las manos y siguió cantando. Hoy sus canciones suenan más fuerte que cualquier tanque. La voz siempre gana.",
    valor: "Voz inmortal",
    url: "https://en.wikipedia.org/wiki/V%C3%ADctor_Jara",
  },
  {
    id: "pablo-larrain",
    tipo: "absurdo",
    titulo: "Director que filmó a Neruda, Pinochet y Lady Di con el mismo ojo crítico",
    descripcion: "Pablo Larraín. Filmó a Neruda, a Pinochet, y a Lady Diana. De Chile a Hollywood sin perder el acento ni la obsesión por lo político.",
    valor: "Cineasta global",
    url: "https://en.wikipedia.org/wiki/Pablo_Larra%C3%ADn",
  },
  {
    id: "sebastian-lelio",
    tipo: "absurdo",
    titulo: "Director que ganó el Oscar con una película sobre una mujer trans chilena",
    descripcion: "Sebastián Lelio ganó el Oscar con una película sobre una mujer trans chilena. Hollywood aplaudió. Chile se hizo el sorprendido.",
    valor: "Oscar 2018",
    url: "https://en.wikipedia.org/wiki/Sebasti%C3%A1n_Lelio",
  },
  {
    id: "gabriel-osorio",
    tipo: "absurdo",
    titulo: "Director que ganó el Oscar con un corto animado sobre un oso y un circo",
    descripcion: "Gabriel Osorio ganó el Oscar con un corto de un oso de peluche. Hizo llorar al mundo entero con stop motion desde La Florida.",
    valor: "Oscar 2016",
    url: "https://en.wikipedia.org/wiki/Historia_de_un_oso",
  },
  {
    id: "pedro-pascal-2",
    tipo: "absurdo",
    titulo: "Actor que pasó de 'Buffy' a ser el papá de Grogu y Joel Miller",
    descripcion: "Pedro Pascal. De Santiago a cuidar a Grogu y sobrevivir hongos zombis. El hombre más cool de Internet es chileno y no lo olvida.",
    valor: "Estrella global",
    url: "https://en.wikipedia.org/wiki/Pedro_Pascal",
  },
  {
    id: "snickers-reyes",
    tipo: "absurdo",
    titulo: "Primer chileno en jugar en la NFL",
    descripcion: "Sammis Reyes. De básquetbol a tight end en Washington. La NFL tuvo su primer chileno. Y no será el último.",
    valor: "NFL 2021",
    url: "https://en.wikipedia.org/wiki/Sammis_Reyes",
  },
  {
    id: "stephanie-vaquer",
    tipo: "absurdo",
    titulo: "Primera mujer chilena y sudamericana campeona de la WWE",
    descripcion: "Stephanie Vaquer. Primera chilena campeona de la WWE. Pasó de los independientes a ganarle a gringas de dos metros en televisión mundial.",
    valor: "WWE Champion",
    url: "https://en.wikipedia.org/wiki/Stephanie_Vaquer",
  },
  {
    id: "futbol-femenino",
    tipo: "absurdo",
    titulo: "Selección femenina que clasificó a su primer Mundial en 2019",
    descripcion: "La Roja femenina clasificó a su primer Mundial en 2019. Mientras tanto, la masculina seguía explicando por qué no. El futuro es femenino, señores.",
    valor: "Francia 2019",
    url: "https://en.wikipedia.org/wiki/Chile_women%27s_national_football_team",
  },
  {
    id: "al-tiro",
    tipo: "absurdo",
    titulo: "Expresión que significa 'inmediatamente' pero nunca es inmediato",
    descripcion: "'Voy al tiro'. Puede ser ahora, en diez minutos, o nunca. Es una promesa etérea, una aspiración temporal.",
    valor: "Flexibilidad cronológica",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "chamullo",
    tipo: "absurdo",
    titulo: "Concepto filosófico que define el arte de hablar sin decir nada",
    descripcion: "Chamullo. Verbo y sustantivo. Es la habilidad de construir discursos vacíos con cara de convicción. Esencial en política.",
    valor: "Deporte nacional intelectual",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "pituto",
    tipo: "absurdo",
    titulo: "Sistema de recomendación laboral que funciona mejor que LinkedIn",
    descripcion: "Pituto. Conseguir trabajo por contactos. Es networking sin el glamour. Es el verdadero motor del empleo.",
    valor: "Capital social",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "cuico",
    tipo: "absurdo",
    titulo: "Término que define a la élite con precisión quirúrgica y resentimiento poético",
    descripcion: "Cuico. Rica, cuica, cuicología. Es clase social, acento, barrio y actitud. Se detecta a kilómetros.",
    valor: "Taxonomía social",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "flaite",
    tipo: "absurdo",
    titulo: "Subcultural urbana con vocabulario propio, moda propia y reglas propias",
    descripcion: "Flaite. Caleta, washita, yal. Es identidad juvenil, resistencia cultural y estilo inconfundible.",
    valor: "Movimiento callejero",
    url: "https://en.wikipedia.org/wiki/Flaite",
  },
  {
    id: "caleta",
    tipo: "absurdo",
    titulo: "Adjetivo que significa 'oculto', 'clandestino' o 'inteligente' según el contexto",
    descripcion: "'Eso está caleta'. Puede ser secreto, puede ser listo, puede ser discreto. El chileno adora lo escondido.",
    valor: "Polisemia nacional",
    url: "https://en.wikipedia.org/wiki/Chilean_Spanish",
  },
  {
    id: "lukas",
    tipo: "absurdo",
    titulo: "Moneda que tiene tres apodos distintos según su denominación",
    descripcion: "Gamba (100), luca/luka (1.000), palo (1.000.000). El peso chileno es tan devaluado que necesita apodos cariñosos.",
    valor: "Léxico monetario",
    url: "https://en.wikipedia.org/wiki/Chilean_peso",
  },
  {
    id: "kiltro",
    tipo: "absurdo",
    titulo: "Perro callejero que es ciudadano de facto de cada población",
    descripcion: "El quiltro vive en la calle, es adoptado por todos, comido por nadie en particular. Es el alma urbana de Chile.",
    valor: "Fauna callejera",
    url: "https://en.wikipedia.org/wiki/Street_dog",
  },
  {
    id: "diablada",
    tipo: "absurdo",
    titulo: "Danza de diablos y ángeles que mezcla catolicismo y cultura andina",
    descripcion: "La Tirana. Diablos con máscaras, baile, y fe en pleno desierto. Es Halloween católico andino. Se juntan el cielo y el infierno por una semana.",
    valor: "Fiesta de La Tirana",
    url: "https://en.wikipedia.org/wiki/Diablada",
  },
  {
    id: "tapati",
    tipo: "absurdo",
    titulo: "Festival ancestral de Rapa Nui que incluye competencias de cuerpo pintado y trineo de banana",
    descripcion: "Tapati Rapa Nui. Dos semanas de cultura polinesia. Haka Pei: bajar un cerro en tronco de banana. Solo en Chile.",
    valor: "Festival único",
    url: "https://en.wikipedia.org/wiki/Tapati_Rapa_Nui",
  },
  {
    id: "mil-tambores",
    tipo: "absurdo",
    titulo: "Festival donde mil tambores llenan las calles de Valparaíso",
    descripcion: "Mil Tambores en Valparaíso. Mil personas desnudas con pintura y tambores tomando los cerros. Es Carnaval, es protesta, es terapia grupal.",
    valor: "Mil Tambores",
    url: "https://en.wikipedia.org/wiki/Carnaval_de_Mil_Tambores",
  },
  {
    id: "viña-del-mar",
    tipo: "absurdo",
    titulo: "Festival de la canción que es más político que musical",
    descripcion: "Viña del Mar. Gaviota de plata, gaviota de oro, monstruo, público exigente. Es el Eurovisión latinoamericano.",
    valor: "Festival #1 Latam",
    url: "https://en.wikipedia.org/wiki/Vi%C3%B1a_del_Mar_International_Song_Festival",
  },
  {
    id: "cacerolazo",
    tipo: "absurdo",
    titulo: "País donde se protesta golpeando cacerolas con cucharas",
    descripcion: "El cacerolazo. Instrumento de cocina convertido en herramienta democrática. Suena a liberación y sopa.",
    valor: "Música de protesta",
    url: "https://en.wikipedia.org/wiki/Cacerolazo",
  },
  {
    id: "evasion-metro",
    tipo: "absurdo",
    titulo: "Movimiento social que empezó por 30 pesos y cambió la Constitución",
    descripcion: "Octubre 2019. Evasión masiva en el Metro. El estallido social. La historia chilena giró en torno a 30 pesos.",
    valor: "Estallido 2019",
    url: "https://en.wikipedia.org/wiki/2019%E2%80%932020_Chilean_protests",
  },
  {
    id: "constitucion",
    tipo: "absurdo",
    titulo: "País que redactó una nueva Constitución por presión ciudadana y luego la rechazó dos veces",
    descripcion: "2020: Apruebo. 2021: Convención. 2022: Rechazo. 2023: Rechazo otra vez. La democracia es un proceso, no un destino.",
    valor: "Proceso constituyente",
    url: "https://en.wikipedia.org/wiki/2022_Chilean_constitutional_referendum",
  },
  {
    id: "bachelet-onu",
    tipo: "absurdo",
    titulo: "Dos veces presidenta que luego dirigió la ONU Mujeres y Derechos Humanos",
    descripcion: "De La Moneda a la ONU. Bachelet pasó de gobernar un país ingobernable a defender los derechos humanos de todo el planeta. Ascenso merecido.",
    valor: "Alta Comisionada ONU",
    url: "https://en.wikipedia.org/wiki/Michelle_Bachelet",
  },
  {
    id: "super-8",
    tipo: "absurdo",
    titulo: "Chocolate en forma de número 8 que es el snack de cine por excelencia",
    descripcion: "Super 8. Chocolate con forma de ocho que se vende en todos los cines chilenos. No es gourmet, pero es el snack de tu infancia y eso no se discute.",
    valor: "Snack cinematográfico",
    url: "https://en.wikipedia.org/wiki/Super_8_(chocolate)",
  },
  {
    id: "chocman",
    tipo: "absurdo",
    titulo: "Galleta con chocolate que es el desayuno de generaciones enteras",
    descripcion: "Chocman, Donuts, Costa. Galletas con cobertura. Desayuno rápido, merienda, cena de emergencia. Es pan integral chileno.",
    valor: "Desayuno nacional",
    url: "https://en.wikipedia.org/wiki/Chocman",
  },
  {
    id: "kem",
    tipo: "absurdo",
    titulo: "Gaseosa de piña que es el sabor oficial de las fondas del 18",
    descripcion: "Kem piña. Bebida amarilla, dulce, artificial. En septiembre se consume por litros. Es el combustible del dieciocho.",
    valor: "Gaseosa patriota",
    url: "https://en.wikipedia.org/wiki/Kem_(drink)",
  },
  {
    id: "fanta",
    tipo: "absurdo",
    titulo: "Gaseosa de naranja que se mezcla con cerveza y se llama 'Fancho'",
    descripcion: "Fanta + schop = Fanschop. Bebida de verano, playa, asado. Los alemanes lloran. Los chilenos brindan.",
    valor: "Fancho supremo",
    url: "https://en.wikipedia.org/wiki/Fanta",
  },
  {
    id: "bases-antarticas",
    tipo: "absurdo",
    titulo: "País con más de 10 bases científicas en la Antártida",
    descripcion: "Más de 10 bases en la Antártida. Tenemos escuelas, familias, y militares congelados. La soberanía se mide en grados bajo cero.",
    valor: "Presencia antártica",
    url: "https://en.wikipedia.org/wiki/Chilean_Antarctic_Territory",
  },
  {
    id: "guanaco",
    tipo: "absurdo",
    titulo: "Camello sin joroba que recorre el desierto y la Patagonia con elegancia",
    descripcion: "El guanaco. Parente de la llama, libre, salvaje. Es el jefe del altiplano y de la estepa. Orgulloso como chileno.",
    valor: "Fauna insignia",
    url: "https://en.wikipedia.org/wiki/Guanaco",
  },
  {
    id: "puma-concolor",
    tipo: "absurdo",
    titulo: "Mayor población de pumas de Sudamérica en Torres del Paine",
    descripcion: "El puma concolor. Gato grande, elegante, letal. En Chile hay más pumas que en cualquier otro lugar del cono sur.",
    valor: "Reino felino",
    url: "https://en.wikipedia.org/wiki/Cougar",
  },
  {
    id: "universidad-chile",
    tipo: "absurdo",
    titulo: "Universidad que tiene más premios nacionales que muchos países vecinos",
    descripcion: "Universidad de Chile. De aquí salieron premios nacionales, presidentes, y el 80% de tus ex que ahora son politólogos en Twitter.",
    valor: "Casa de Bello",
    url: "https://en.wikipedia.org/wiki/University_of_Chile",
  },
  {
    id: "catolica",
    tipo: "absurdo",
    titulo: "Universidad que formó a la derecha chilena moderna con excelencia académica",
    descripcion: "UC Chile. Formó empresarios, políticos, y la élite que maneja el país desde el punto de vista del Señor. Dios y el mercado en una sola carrera.",
    valor: "Alma mater",
    url: "https://en.wikipedia.org/wiki/Pontifical_Catholic_University_of_Chile",
  },
  {
    id: "quinchere",
    tipo: "absurdo",
    titulo: "Baile típico donde dos personas giran agarradas de un pañuelo",
    descripcion: "El pericón, la trastrasera, el costillar. Bailes de Chiloé y el sur. Es folclor con más energía que zumba.",
    valor: "Baile sureño",
    url: "https://en.wikipedia.org/wiki/Chilean_folk_dance",
  },
  {
    id: "berlin-chileno",
    tipo: "absurdo",
    titulo: "Facturas alemanas que se comen en panaderías de todo Chile",
    descripcion: "Berlines. Masa frita, relleno de crema o manjar. Son donas alemanas chilenizadas. Hay más berlines que alemanes.",
    valor: "Factura germana",
    url: "https://en.wikipedia.org/wiki/Berliner_(pastry)",
  },
  {
    id: "palta-reina",
    tipo: "absurdo",
    titulo: "Plato donde una palta es el recipiente de ensalada de pollo",
    descripcion: "Palta reina: aguacate partido, relleno de pollo con mayonesa. Es un plato que usa fruta como plato. Genialidad culinaria.",
    valor: "Fruta como bowl",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "tomates-rellenos",
    tipo: "absurdo",
    titulo: "Vegetal que se convierte en recipiente de ensalada de choclo y mayonesa",
    descripcion: "Tomates rellenos. Choclo, cebolla, mayo dentro de un tomate. Es naturaleza rellenando naturaleza.",
    valor: "Ingenio veraniego",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "arrollado-huaso",
    tipo: "absurdo",
    titulo: "Rollo de carne condimentado que es el fiambre de campo por excelencia",
    descripcion: "Arrollado de huaso. Carne de cerdo, ajo, pimienta, envuelto. Se corta en fetas. Es el embutido de la independencia.",
    valor: "Fiambre criollo",
    url: "https://en.wikipedia.org/wiki/Arrollado_de_huaso",
  },
  {
    id: "prietas",
    tipo: "absurdo",
    titulo: "Morcilla que se come con papas cocidas y chucrut en el sur",
    descripcion: "Prietas con papas. Sangre, cebolla, arroz, envuelto. Es el hot dog del campo chilote.",
    valor: "Embutido sureño",
    url: "https://en.wikipedia.org/wiki/Chilean_cuisine",
  },
  {
    id: "chapalele",
    tipo: "absurdo",
    titulo: "Ñoqui de papa que acompaña al curanto y al cordero al palo",
    descripcion: "Chapalele. Papa con harina hervida que acompaña al curanto. Es ñoqui sureño, pero con más raíces y menos pretensión italiana.",
    valor: "Acompañamiento esencial",
    url: "https://en.wikipedia.org/wiki/Chapalele",
  },
  {
    id: "milcao",
    tipo: "absurdo",
    titulo: "Tortilla de papa cruda y cocida que solo existe en Chiloé",
    descripcion: "Milcao. Papa rallada cruda, papa cocida, chicharrón. Se fríe. Es el hash brown chilote, pero con alma.",
    valor: "Patrimonio chilote",
    url: "https://en.wikipedia.org/wiki/Milcao",
  },
  {
    id: "chuchoca",
    tipo: "absurdo",
    titulo: "Harina de maíz tostada que se espesa en leche como desayuno ancestral",
    descripcion: "Chuchoca con leche. Maíz tostado molido, hervido en leche. Es el cereal de los abuelos. Nutritivo y eterno.",
    valor: "Desayuno ancestral",
    url: "https://en.wikipedia.org/wiki/Chuchoca",
  },
  {
    id: "mote-con-huesillo-final",
    tipo: "absurdo",
    titulo: "Refrigerio que ha sobrevivido a todos los gobiernos desde 1810",
    descripcion: "Democracia, dictadura, democracia. El mote con huesillo sigue ahí. Es más estable que el sistema político.",
    valor: "Institución nacional",
    url: "https://en.wikipedia.org/wiki/Mote_con_huesillo",
  },
];
